config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'register/index'
  resources:articles

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true,
                    length: { minimum: 3 }
end

app/models/register.rb
class Register < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
 
  def show
    @article = Article.find(params[:id])
  end
 
  def new
    @article = Article.new
  end
 
  def edit
    @article = Article.find(params[:id])
  end
 
  def create
    @article = Article.new(article_params)
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
 
  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
 
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end
 
  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/data_controllers.rb
class DataController < ApplicationController
	def index
    @register = Register.all
  end

 def create
  @register = Register.new(params[:register])
 
  @register.save
  redirect_to @register
end
private
  def register_params
    params.require(:article).permit(:firstname, :lastname, :email , :address , :telephone)
  end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  def index
 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= form_with(model: @article) do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>
<%= form_for :article, url: articles_path do |f| %>
<% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

 <p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
  
  </head>

  <body>
  
    <%= yield %>
  </body>
</html>

app/views/register/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
.myRegister {
  text-align: center;
  background-color: tomato;
  color: white;
  padding: 10px;
}
</style>

<h1 class = "myRegister">Register</h1>
<form>
<div class="form-group">
  First name:<br>
  <input class="form-control" type="text" name="firstname"><br>
  Last name:<br>
  <input type="text" name="lastname"><br>
  Email:<br>
  <input type="text" name="email"><br>
  Address:<br>
  <input type="text" name="address"><br>
  Telephone:<br>
  <input type="text" name="telephone"><br><br>
  <input type="submit" value="Submit">
  </div>
</form>
</head>
</html>

app/views/register/new.html.erb
<h1>New Register</h1>
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>
<%= form_for :register, url: articles_path do |f| %>
<% if @register.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@register.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @register.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </p>
 <p>
    <%= form.label :lastname %><br>
    <%= form.text_area :lastname %>
  </p>
   <p>
    <%= form.label :email %><br>
    <%= form.text_area :email %>
  </p>
   <p>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </p>
   <p>
    <%= form.label :telephone %><br>
    <%= form.text_area :telephone %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', register_path %>

app/views/register/show.html.erb
<p>
  <strong>Firstname:</strong>
  <%= @register.firstname %>
</p>
 
<p>
  <strong>Surname:</strong>
  <%= @register.surname %>
</p>
<p>
  <strong>Email:</strong>
  <%= @register.email %>
</p>
 
<p>
  <strong>Address:</strong>
  <%= @register.address %>
</p>
<p>
  <strong>Telephone:</strong>
  <%= @register.telephone %>
</p>

app/views/welcome/index.html.erb
<h1>Hello,Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>